import '../messages.dart';

const hypErrors = {
  "1": Errors.blockCard,
  "2": Errors.stolenCard,
  "3": Errors.callCreditCompany,
  "4": Errors.transactionNotConfirmed,
  "5": Errors.fakeCard,
  "6": Errors.wrongCVV,
  "7": Errors.worngCAVVUCAF,
  "8": Errors.worngAvs,
  "9": Errors.networkDisconnect,
  "10": Errors.partlyConfirm,
  "11": Errors.lackOfPointsStarsMilesOtherBenefit,
  "12": Errors.unauthorizedCardAtTheTerminal,
  "13": Errors.invalidBalanceCode,
  "14": Errors.cardNotAssociatedWithTheNetwork,
  "15": Errors.cardIsNotValid,
  "16": Errors.currencyTypeIsNotAllowed,
  "17": Errors.thereIsNoAuthorizationForACreditTypeInTheTransaction,
  "26": Errors.invalidId,
  "901": Errors
      .terminalNotAuthorizedToWorkWithThisMethodTheTerminalIsNotAuthorized,
  "902": Errors.authenticationErrorTerminalReference,
  "903": Errors.exceedingTheNumberOfPayments,
  "999": Errors.communicationError,
  "998": Errors.canceledTransaction,
  "997": Errors.invalidToken,
  "996": Errors.terminalNotAuthorizedToUseTheToken,
  "800": Errors.deferredCharge,
  "700": Errors.approvalWithoutCharge,
  "600": Errors.receivingTransactionDetails,
  "990": Errors.theCardDetailsWereNotReadInFull,
  "400": Errors.theAmountOfTheItemsDoesNotMatch,
  "401": Errors.YouMustEnterAFirstOrLastName,
  "402": Errors.transactionDescriptionMustBeEntered,
  "33": Errors.youCanCreditTheEntireTransactionOrASmallAmount,
};
