export enum BusinessesTypes {
  Barber,
  Polish,
  Beautician,
  ManicurePedicure,
  Eyelashes,
  Eyebrows,
  Braids,
  MakeUpArtist,
  TattooArtist,
  HairRemoval,
  Masseur,
  Physiotherapy,
  Cobblers,
  Clown,
  SocialWorker,
  Magician,
  Doctor,
  Veterinarian,
  CommunicationTherapist,
  DogGroomer,
  DJ,
  Psychologist,
  Tutor,
  WeddingDresses,
  DanceTeacher,
  Babysitter,
  Reflexologist,
  Dietitian,
  CarWash,
  Photographer,
  SwimmingTeacher,
  Counselor,
  Mentor,
  TennisCoach,
  PrivateChef,
  PersonalTrainer,
  Lawyer,
  Sales,
  RealEstate,
  DrivingTeacher,
  InvestmentAdvice,
  Library,
  Tailor,
  Restaurant,
  NailConstruction,
  Dentist,
  BeautysSalon,
  Washer,
  CleaningSofas,
  Other,
}

export const businessTypeToStr: { [key in BusinessesTypes]: string } = {
  [BusinessesTypes.Barber]: "barber",
  [BusinessesTypes.Polish]: "polish",
  [BusinessesTypes.CleaningSofas]: "cleaningSofas",
  [BusinessesTypes.Beautician]: "beautician",
  [BusinessesTypes.ManicurePedicure]: "manicurePedicure",
  [BusinessesTypes.Eyelashes]: "eyelashes",
  [BusinessesTypes.Eyebrows]: "eyebrows",
  [BusinessesTypes.Babysitter]: "babysitter",
  [BusinessesTypes.Braids]: "braids",
  [BusinessesTypes.MakeUpArtist]: "makeUpArtist",
  [BusinessesTypes.TattooArtist]: "tattooArtist",
  [BusinessesTypes.HairRemoval]: "hairRemoval",
  [BusinessesTypes.Masseur]: "masseur",
  [BusinessesTypes.Cobblers]: "cobblers",
  [BusinessesTypes.Clown]: "clown",
  [BusinessesTypes.SocialWorker]: "socialWorker",
  [BusinessesTypes.Magician]: "magician",
  [BusinessesTypes.Doctor]: "doctor",
  [BusinessesTypes.DJ]: "dj",
  [BusinessesTypes.Veterinarian]: "veterinarian",
  [BusinessesTypes.CommunicationTherapist]: "communicationTherapist",
  [BusinessesTypes.DogGroomer]: "dogGroomer",
  [BusinessesTypes.Psychologist]: "psychologist",
  [BusinessesTypes.Physiotherapy]: "physiotherapy",
  [BusinessesTypes.Tutor]: "Tutor",
  [BusinessesTypes.WeddingDresses]: "weddingDresses",
  [BusinessesTypes.DanceTeacher]: "danceTeacher",
  [BusinessesTypes.Reflexologist]: "reflexologist",
  [BusinessesTypes.Dietitian]: "dietitian",
  [BusinessesTypes.CarWash]: "carWash",
  [BusinessesTypes.Photographer]: "photographer",
  [BusinessesTypes.SwimmingTeacher]: "swimmingTeacher",
  [BusinessesTypes.Counselor]: "counselor",
  [BusinessesTypes.Mentor]: "mentor",
  [BusinessesTypes.TennisCoach]: "tennisCoach",
  [BusinessesTypes.PrivateChef]: "privateChef",
  [BusinessesTypes.PersonalTrainer]: "personalTrainer",
  [BusinessesTypes.Lawyer]: "lawyer",
  [BusinessesTypes.Sales]: "sales",
  [BusinessesTypes.RealEstate]: "realEstate",
  [BusinessesTypes.DrivingTeacher]: "drivingTeacher",
  [BusinessesTypes.InvestmentAdvice]: "investmentAdvice",
  [BusinessesTypes.Library]: "library",
  [BusinessesTypes.Other]: "other",
  [BusinessesTypes.Tailor]: "tailor",
  [BusinessesTypes.Restaurant]: "restaurant",
  [BusinessesTypes.NailConstruction]: "nailConstruction",
  [BusinessesTypes.Dentist]: "dentist",
  [BusinessesTypes.BeautysSalon]: "beautysSalon",
  [BusinessesTypes.Washer]: "washer",
};

export const businessTypesToIcon: { [key in BusinessesTypes]: string } = {
  [BusinessesTypes.Barber]: "assets/icons/barber.webp",
  [BusinessesTypes.Polish]: "assets/icons/nail-polish.webp",
  [BusinessesTypes.Other]: "assets/icons/more-information.webp",
  [BusinessesTypes.Beautician]: "assets/icons/hairdresser.webp",
  [BusinessesTypes.ManicurePedicure]: "assets/icons/finger-with-nail.webp",
  [BusinessesTypes.Babysitter]: "assets/icons/mother.webp",
  [BusinessesTypes.Eyelashes]: "assets/icons/eye.webp",
  [BusinessesTypes.Eyebrows]: "assets/icons/liner.webp",
  [BusinessesTypes.Braids]: "assets/icons/wig.webp",
  [BusinessesTypes.MakeUpArtist]: "assets/icons/make-up.webp",
  [BusinessesTypes.TattooArtist]: "assets/icons/tattoo.webp",
  [BusinessesTypes.HairRemoval]: "assets/icons/hair-removal.webp",
  [BusinessesTypes.Masseur]: "assets/icons/masseur.webp",
  [BusinessesTypes.Cobblers]: "assets/icons/cobbler.webp",
  [BusinessesTypes.Clown]: "assets/icons/clown.webp",
  [BusinessesTypes.SocialWorker]: "assets/icons/social-care.webp",
  [BusinessesTypes.Magician]: "assets/icons/hat.webp",
  [BusinessesTypes.Physiotherapy]: "assets/icons/physical-therapy.webp",
  [BusinessesTypes.Doctor]: "assets/icons/stethoscope.webp",
  [BusinessesTypes.Veterinarian]: "assets/icons/veterinarian.webp",
  [BusinessesTypes.CommunicationTherapist]: "assets/icons/communication.webp",
  [BusinessesTypes.DogGroomer]: "assets/icons/groomer.webp",
  [BusinessesTypes.DJ]: "assets/icons/dj.webp",
  [BusinessesTypes.Psychologist]: "assets/icons/psychologist.webp",
  [BusinessesTypes.Tutor]: "assets/icons/teacher.webp",
  [BusinessesTypes.WeddingDresses]: "assets/icons/wedding-dress.webp",
  [BusinessesTypes.DanceTeacher]: "assets/icons/dancing.webp",
  [BusinessesTypes.Reflexologist]: "assets/icons/knee.webp",
  [BusinessesTypes.Dietitian]: "assets/icons/diet.webp",
  [BusinessesTypes.CarWash]: "assets/icons/car-wash.webp",
  [BusinessesTypes.Photographer]: "assets/icons/photographer.webp",
  [BusinessesTypes.SwimmingTeacher]: "assets/icons/swimming.webp",
  [BusinessesTypes.Counselor]: "assets/icons/discussion.webp",
  [BusinessesTypes.Mentor]: "assets/icons/leadership.webp",
  [BusinessesTypes.TennisCoach]: "assets/icons/coach.webp",
  [BusinessesTypes.PrivateChef]: "assets/icons/chef.webp",
  [BusinessesTypes.PersonalTrainer]: "assets/icons/fitness.webp",
  [BusinessesTypes.Lawyer]: "assets/icons/lawyer.webp",
  [BusinessesTypes.Sales]: "assets/icons/sales.webp",
  [BusinessesTypes.RealEstate]: "assets/icons/real-estate.webp",
  [BusinessesTypes.DrivingTeacher]: "assets/icons/steering-wheel.webp",
  [BusinessesTypes.InvestmentAdvice]: "assets/icons/financial-profit.webp",
  [BusinessesTypes.Library]: "assets/icons/book.webp",
  [BusinessesTypes.Tailor]: "assets/icons/suit.webp",
  [BusinessesTypes.Restaurant]: "assets/icons/restaurant.webp",
  [BusinessesTypes.NailConstruction]: "assets/icons/nail-dryer.webp",
  [BusinessesTypes.Dentist]: "assets/icons/tooth.webp",
  [BusinessesTypes.BeautysSalon]: "assets/icons/bueaty-salon.webp",
  [BusinessesTypes.Washer]: "assets/icons/washer.webp",
  [BusinessesTypes.CleaningSofas]: "assets/icons/sofa.webp",
};

export const businessTypeFromStr: { [key: string]: BusinessesTypes } = {
  barber: BusinessesTypes.Barber,
  cleaningSofas: BusinessesTypes.CleaningSofas,
  polish: BusinessesTypes.Polish,
  beautician: BusinessesTypes.Beautician,
  manicurePedicure: BusinessesTypes.ManicurePedicure,
  eyelashes: BusinessesTypes.Eyelashes,
  eyebrows: BusinessesTypes.Eyebrows,
  babysitter: BusinessesTypes.Babysitter,
  braids: BusinessesTypes.Braids,
  makeUpArtist: BusinessesTypes.MakeUpArtist,
  tattooArtist: BusinessesTypes.TattooArtist,
  hairRemoval: BusinessesTypes.HairRemoval,
  masseur: BusinessesTypes.Masseur,
  cobblers: BusinessesTypes.Cobblers,
  clown: BusinessesTypes.Clown,
  socialWorker: BusinessesTypes.SocialWorker,
  magician: BusinessesTypes.Magician,
  doctor: BusinessesTypes.Doctor,
  veterinarian: BusinessesTypes.Veterinarian,
  communicationTherapist: BusinessesTypes.CommunicationTherapist,
  dogGroomer: BusinessesTypes.DogGroomer,
  psychologist: BusinessesTypes.Psychologist,
  physiotherapy: BusinessesTypes.Physiotherapy,
  Tutor: BusinessesTypes.Tutor,
  weddingDresses: BusinessesTypes.WeddingDresses,
  danceTeacher: BusinessesTypes.DanceTeacher,
  reflexologist: BusinessesTypes.Reflexologist,
  dietitian: BusinessesTypes.Dietitian,
  carWash: BusinessesTypes.CarWash,
  photographer: BusinessesTypes.Photographer,
  swimmingTeacher: BusinessesTypes.SwimmingTeacher,
  counselor: BusinessesTypes.Counselor,
  mentor: BusinessesTypes.Mentor,
  dj: BusinessesTypes.DJ,
  tennisCoach: BusinessesTypes.TennisCoach,
  privateChef: BusinessesTypes.PrivateChef,
  personalTrainer: BusinessesTypes.PersonalTrainer,
  lawyer: BusinessesTypes.Lawyer,
  sales: BusinessesTypes.Sales,
  realEstate: BusinessesTypes.RealEstate,
  drivingTeacher: BusinessesTypes.DrivingTeacher,
  investmentAdvice: BusinessesTypes.InvestmentAdvice,
  library: BusinessesTypes.Library,
  other: BusinessesTypes.Other,
  restaurant: BusinessesTypes.Restaurant,
  tailor: BusinessesTypes.Tailor,
  nailConstruction: BusinessesTypes.NailConstruction,
  dentist: BusinessesTypes.Dentist,
  beautysSalon: BusinessesTypes.BeautysSalon,
  washer: BusinessesTypes.Washer,
};

//   const businessesTypeToImages: { [key in BusinessesTypes]: { [key: string]: string } } = {
//     [BusinessesTypes.Barber]: {
//       'assets/images/barber_image_1.webp': 'white',
//       'assets/images/barber_image_2.webp': 'white',
//       'assets/images/barber_image_3.webp': 'white',
//     },
//     [BusinessesTypes.Polish]: {
//       'assets/images/polish_image_1.webp': 'black',
//       'assets/images/polish_image_2.webp': 'black',
//       'assets/images/polish_image_3.webp': 'black',
//     },
//     [BusinessesTypes.MakeUpArtist]: {
//       'assets/images/beautician_image_1.webp': 'black',
//       'assets/images/beautician_image_2.webp': 'black',
//       'assets/images/beautician_image_3.webp': 'black',
//     },
//     [BusinessesTypes.TattooArtist]: {
//       'assets/images/tatoo_image_1.webp': 'white',
//       'assets/images/tatoo_image_2.webp': 'white',
//       'assets/images/tatoo_image_3.webp': 'white',
//     },
//     [BusinessesTypes.PrivateChef]: {
//       'assets/images/chef_image_1.webp': 'white',
//       'assets/images/chef_image_2.webp': 'white',
//       'assets/images/chef_image_3.webp': 'white',
//     },
//     [BusinessesTypes.PersonalTrainer]: {
//       'assets/images/fitness_image_1.webp': 'white',
//       'assets/images/fitness_image_2.webp': 'white',
//       'assets/images/fitness_image_3.webp': 'white',
//     },
//   };
