name: Docker Build & Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t simpletorweb:latest .
          docker tag simpletorweb:latest 339713099835.dkr.ecr.il-central-1.amazonaws.com/simpletor-svelte-app:latest
          docker push 339713099835.dkr.ecr.il-central-1.amazonaws.com/simpletor-svelte-app:latest
